### ISSUE TITLE
Add function register_query_handler_inside_udf

### ISSUE THREAD

**Issue by ckunki** [exasol/advanced-analytics-framework#197] opened 2024-10-11 10:15 UTC
### Acceptance Criteria
* The register function e.g. `register_query_handler_inside_udf()` is added to AAF python code 
* The register function should add the udf to module `exasol_advanced_analytics_framework.custom`, so we need to add an empty module at this place
* The register function is included in the adhoc example of the user guide incl. a comment that it only needs to be called when defining the query handler inside of a UDF (= adhoc)

**Comment by tkilias** [comment] 2024-10-11 12:46
the register_query_handler_inside_udf function should add the udf to module exasol_advanced_analytics_framework.custom, so we need to add an empty module at this place

**Comment by tkilias** [comment] 2024-10-28 09:16
duplicate of https://github.com/exasol/advanced-analytics-framework/issues/190

**Closed by tkilias** 2024-10-28 09:16 UTC
Labels: refactoring
